variables:
  APP_NAME: jules
  API_ENDPOINT: ip10-0-1-3-ceiub28mjkegg872c2vg-1996.direct.docker.labs.eazytraining.fr
  STG_APP_ENDPOINT: ip10-0-1-3-ceiub28mjkegg872c2vg-81.direct.docker.labs.eazytraining.fr
  PROD_APP_ENDPOINT: ip10-0-1-3-ceiub28mjkegg872c2vg-80.direct.docker.labs.eazytraining.fr
  INTERNAL_PORT: 3000
  EXTERNAL_PORT: 80
  STG_EXTERNAL_PORT: 81
  PROD_EXTERNAL_PORT: 80
  CONTAINER_IMAGE: ${IMAGE_NAME}:${CI_COMMIT_REF_NAME}

# Official docker image.
image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build image
  - Run image
  - Release image
  - Deploy staging
  - Test staging
  - Deploy prod
  - Test prod

before_script:
  - echo "Welcome to mini Gitlab-CI mini-project"

.job A:
  stage: Build image
  script:
    - docker build -t static_website .
    - docker save static_website > static_website.tar
  artifacts:
    paths:
      - "static_website.tar"
    untracked: false
    when: on_success
    expire_in: 30 days

.job B:
  stage: Run image
  script:
    - docker load < static_website.tar
    - docker run -d -p ${EXTERNAL_PORT}:${INTERNAL_PORT} --name website static_website
    - apk --no-cache add curl
    - sleep 5
    - curl "http://docker:${EXTERNAL_PORT}" | grep -i "Dimension"

.job C:
  stage: Release image
  script:
    - docker load < static_website.tar
    - docker tag static_website "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"

.deploy_template: &test
  image: alpine
  only:
    - main
  script:
    - apk --no-cache add curl
    - curl "http://$DOMAIN" || grep -i "Dimension"

job D:
  stage: Deploy staging
  environment:
    name: staging
    url: http://${STG_APP_ENDPOINT}
  only:
    - main
  script:
    - apk --no-cache add curl
    - echo ${API_ENDPOINT} ${APP_NAME} ${CONTAINER_IMAGE} ${STG_EXTERNAL_PORT} ${INTERNAL_PORT} ${STG_APP_ENDPOINT}
    - 'curl -X POST http://${API_ENDPOINT}/staging -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${STG_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

job H:
  stage: Test staging
  <<: *test
  variables:
    DOMAIN: ${STG_APP_ENDPOINT}

job E:
  stage: Deploy prod
  environment:
    name: prod
    url: http://${PROD_APP_ENDPOINT}
  only:
    - main
  script:
    - apk --no-cache add curl
    - 'curl -X POST http://${API_ENDPOINT}/prod -H "Content-Type: application/json" -d "{\"your_name\":\"${APP_NAME}\",\"container_image\":\"${CONTAINER_IMAGE}\", \"external_port\":\"${PROD_EXTERNAL_PORT}\", \"internal_port\":\"${INTERNAL_PORT}\"}"'

job I:
  stage: Test prod
  <<: *test
  variables:
    DOMAIN: ${PROD_APP_ENDPOINT}

after_script:
  - echo "End baye !!"
